Streamline readme with getting-started structure
QuickLogic-Corp/qorc-sdk pull request #49
Opened 2020-10-05 17:08 UTC by coolbreeze413

Updated the following parts in the readme:
1. update users to do a recursive clone instead of a normal clone
2. update steps to install GCC Arm Embedded toolchain from archive, which is the correct method now, as PPA has been deprecated for some time
3. remove TinyFPGA programmer instructions from here (will add these details to the TinyFPGA programmer repo instead)

2020-10-05 19:48 UTC, timsaxe requested changes
1. [Must have for this PR] The CI does not use the same repo as the instructions suggest,  That needs to be changed. (Side note, I think we need to create a 'setup.bash' script that both CI and the user can use -- something for the future)
2. [Note -- not for this PR] The recursive is OK for now, but will become a problem when we get large submodules such as tensorflow.  I propose we solve this by have a setup.bash that has a notion of the default install and allows the user to add or delete from that -- again for the future.
3. [Note -- not for this PR] I personally find it annoying to have to read multiple docs to get an install done.  I think there are two ways to help with this. a/ if we have the setup.csh then we can make the tinyfpga and symbiflow installs part of that, or b/ since Sphinx combines docs we can have the instructions in that.

2020-10-08 16:08 UTC, coolbreeze413 commented
1. Added the new steps to CI as well, and see that it passes.
2,3 : Both of these would be addressed using a release or init script which can:
- checkout TinyFPGA Programmer in the qorc-sdk tree, automatically add path and create alias
- download and run Symbiflow installer, add path and env vars (or switch to docker based approach)
Also, with sphinx based readthedocs, we can have a detailed step by step instruction set, rather than a disjointed set of readmes.
I will note this for the sphinx based documentation task.

2020-10-08 18:59 UTC, timsaxe requested changes
This looks like a good step forward.  One point that I am not clear on is that ISSUE#42 points out there is a problem when there are multiple gcc tool chains installed.  I know we haven;t made the changes to support multiple gcc, so my question is whether this install is compatible with that i.e. only changes to other tools are required, or will this have to change as well?  And if this has to change, what is the recommendation: go ahead with this and accept a further change in the future, or make the change now?

2020-10-08 19:31 UTC, coolbreeze413 commented
Yes this is a problem. This is bound to happen on systems where multiple toolchains are installed which is the case for most of the end users - working simultaneously on multiple platforms, using different versions of gcc, and we would need to account for the fact that the user may already have multiple gcc versions on the path.
For our case, I think it is a good way to fix the path that we are using in the makefile as suggested in #42 so that there is a specific variable for QORC, and use that (QORC_TC_PATH as suggested is good).
Then instead of 
`export PATH=/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/:$PATH`
we need to do
`export QORC_TC_PATH=/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/`
and then proceed as usual.
If this is not defined, the make process can specifically instruct the user to define this env variable before attempting to build.

I will check if this process can have any problems with some combinations on my system, but I think it is a good approach.
I will update after some testing.

2020-10-08 19:50 UTC, timsaxe commented
Great.  Thanks for taking this up.  We can generalize that most things should use a specific name: symbiflow path, cond env, etc

Tim

From: Krishna Kumar <notifications@github.com>
Sent: Thursday, October 8, 2020 12:32 PM
To: QuickLogic-Corp/qorc-sdk <qorc-sdk@noreply.github.com>
Cc: Tim Saxe <Saxe@quicklogic.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [QuickLogic-Corp/qorc-sdk] Streamline readme with getting-started structure (#49)


Yes this is a problem. This is bound to happen on systems where multiple toolchains are installed which is the case for most of the end users - working simultaneously on multiple platforms, using different versions of gcc, and we would need to account for the fact that the user may already have multiple gcc versions on the path.
For our case, I think it is a good way to fix the path that we are using in the makefile as suggested in #42<https://github.com/QuickLogic-Corp/qorc-sdk/issues/42> so that there is a specific variable for QORC, and use that (QORC_TC_PATH as suggested is good).
Then instead of
export PATH=/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/:$PATH
we need to do
export QORC_TC_PATH=/usr/share/gcc-arm-none-eabi-9-2020-q2-update/bin/
and then proceed as usual.
If this is not defined, the make process can specifically instruct the user to define this env variable before attempting to build.

I will check if this process can have any problems with some combinations on my system, but I think it is a good approach.
I will update after some testing.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/QuickLogic-Corp/qorc-sdk/pull/49#issuecomment-705777842>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO4FHELFU6UWKLHCVAWX5ODSJYHSHANCNFSM4SE6NJLA>.

2020-10-15 18:24 UTC, coolbreeze413 commented
For hardening the makefile to work correctly even with multiple gcc arm embedded toolchains, we can change the `config.mk` file to:
- remove the `FIND_TOOL_DIR` step
- rename `TC_PATH` to `QORC_TC_PATH`

so that if `QORC_TC_PATH` is not set, the makefile throws an error to the user asking to define the environment variable.  
If `QORC_TC_PATH` is set, and even if the toolchain is not added to path, it works fine, so adding to the path is not needed.

For the Symbiflow toolchain, I haven't checked yet, but I think we need only something like a `QLSYMBIFLOW_TC_PATH` defined, and `export PATH="$QLSYMBIFLOW_TC_PATH/install/bin:$QLSYMBIFLOW_TC_PATH/install/bin/python:$PATH"` done.
The other steps:
```
source "$INSTALL_DIR/conda/etc/profile.d/conda.sh"
conda activate
... build
conda deactivate
```
can theoretically be added to the appfpga makefile, however we need to check and do some more testing to be sure.

I feel that we can target the changes for the multiple-gcc-toolchains problem in a separate PR, created for #42 instead of in this PR.
For the Symbiflow toolchain, we can check and tackle that separately.

Please let me know if that seems to be ok ?

2020-10-20 13:57 UTC, coolbreeze413 commented
separate PR created for hardening gcc build with possibly multiple gcc-arm-embedded toolchains installed:  #63  
current PR only has readme changes for correcting installation method of gcc-arm-embedded toolchain via the tarball, and update of the CI to use the same method.  
once approved, can be merged.

2020-11-02 21:18 UTC, murthyvedula approved these changes

2020-11-02 21:20 UTC, murthyvedula commented
> 
> 
> This looks like a good step forward. One point that I am not clear on is that ISSUE#42 points out there is a problem when there are multiple gcc tool chains installed. I know we haven;t made the changes to support multiple gcc, so my question is whether this install is compatible with that i.e. only changes to other tools are required, or will this have to change as well? And if this has to change, what is the recommendation: go ahead with this and accept a further change in the future, or make the change now?

issue #42 multiple gcc toolchain support will be added as part of PR #63

2020-11-02 21:22 UTC, merged